//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Login
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Email ID is Required ")]
        [DisplayName("Email ID")]
        public string Email_ID { get; set; }

        [Required(ErrorMessage = "Password is Required ")]

        public string Password { get; set; }
    }
}
