//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        

        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "It is required to select one category")]
        public string Category { get; set; }

        [Required(ErrorMessage = "Price is required")]
        public double Price { get; set; }

        [Required(ErrorMessage = "One of the quantity is must to select")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "Short Description is required")]
        [DisplayName("Short Description")]

        public string Short_Description { get; set; }

        [DisplayName("Long Description")]
        public string Long_Description { get; set; }

        [DisplayName("Small Image")]
        [Required(ErrorMessage = "Small Image is required")]
        public string Small_Image { get; set; }

        [DisplayName("Large Image")]
        public string Large_Image { get; set; }

        public HttpPostedFileBase file { get; set; }

    }
}
