//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignupWithLogin.Models
{
    using SignupWithLogin.Custom_Validation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "First name is a required field")]
        [StringLength(10, MinimumLength=3, ErrorMessage = "Enter the First name with minimum length 3 and maximum length 10")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is a required field")]
        [StringLength(10, MinimumLength = 3, ErrorMessage = "Enter the Last name with minimum length 3 and maximum length 10")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Gender is a required field")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Date Of Birth is a required field")]
        [DataType(DataType.Date)]
        [ValidBirthDate(ErrorMessage = "DOB Should be between 01-25-1970 & 01-25-2000")]

        public System.DateTime DOB { get; set; }

        [Required(ErrorMessage = "Age is a required field")]
        [Range(18, 30, ErrorMessage = "Age must be from 18 to 30 years")]

        public int Age { get; set; }

        [Required(ErrorMessage = "Phone is a required field")]
        [DataType(DataType.PhoneNumber)]
        

        public int Phone { get; set; }

        

        [Required(ErrorMessage = "Email is a required field")]
        [RegularExpression("^([0-9a-zA-Z]([-\\.\\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$",ErrorMessage ="Invalid Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "user name is a required field")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is a required field")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm Password is a required field")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage ="Password is not Identical")]
        public string Confirm_Password { get; set; }

        [Required(ErrorMessage = "File is a required field")]
        [DisplayName("Upload File")]
        [FileExtensions(ErrorMessage = "Select image only", Extensions = "jpg,png,jpeg")]
        public byte[] File { get; set; }

        [CheckRequired(ErrorMessage ="Please accept terms and conditions")]
        public bool IsTerms { get; set; }


    }
}
